name: Prepare iOS build environment
description: Prepare application's build environment

inputs:
  match-git-private-key-content:
    description: 'Required input to set Match git private key content'
    required: true

runs:
  using: composite
  steps:
    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: yarn

    - name: Set up ruby env
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.4'
        bundler-cache: true
        working-directory: ios

    - name: Install dependencies
      run: yarn install --immutable --immutable-cache --check-cache
      shell: bash

    - uses: actions/cache@v4
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Install iOS pods
      run: pod install
      working-directory: ios
      shell: bash

    - name: Generate Git private key for Match
      env:
        MATCH_GIT_PRIVATE_KEY: ${{ inputs.match-git-private-key-content }}
      run: |
        echo "$MATCH_GIT_PRIVATE_KEY" > match-git-key.pem
        chmod 400 match-git-key.pem
      working-directory: ios
      shell: bash
