default_platform(:ios)

platform :ios do
  private_lane :build do |options|
    type = (options[:type] || "development")
    export_method = (options[:export_method] || "development")

	if is_ci
		setup_ci
	end
	sync_code_signing(type: type, readonly: true)

	update_code_signing_settings()
	build_ios_app(export_method: export_method, silent: true)
  end

  private_lane :increment_version do |options|
	increment_build_number(build_number: ENV['VERSION_CODE'])
	increment_version_number(version_number: ENV['VERSION_NAME'])
  end

  desc "Continuous integration"
  lane :ci do
       build(type: "development", export_method: "development")
  end

  desc "Release to TestFlight for internal testing"
  lane :publish_testflight do
       app_store_connect_api_key
       increment_version
       build(type: "appstore", export_method: "app-store")
       upload_to_testflight(changelog: ENV['RELEASE_NOTES'])
  end
end
