default_platform(:ios)

platform :ios do
  private_lane :build do |options|
    type = (options[:type] || "development")

	if is_ci
		setup_ci
	end
	sync_code_signing(
	    type: type,
	    readonly: true
	)
	update_code_signing_settings
	build_ios_app(
        export_method: type,
        silent: true
	)
  end

  desc "Continuous integration"
  lane :ci do
       build(type: "development")
  end
end
