default_platform(:ios)

platform :ios do
  desc "Continuous integration"
  lane :ci do
	if is_ci
		setup_ci
	end
	sync_code_signing(
	    type: "development",
	    readonly: true
	)
	update_code_signing_settings
	build_ios_app(
        export_method: "development",
        silent: true
	)
  end
end
