name: Prepare Android build environment
description: Prepare application's build environment

runs:
  using: composite
  steps:
    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: yarn

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
        cache: gradle

    - name: Set up ruby env
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.4'
        bundler-cache: true
        working-directory: android

    - name: Install dependencies
      run: yarn install --immutable --immutable-cache --check-cache
      shell: bash
