name: Continuous integration

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare build environment
        uses: ./.github/actions/prepare-android-build-environment

      - name: Android build test
        run: bundle exec fastlane android ci
        working-directory: android
        env:
          # Full path is required by Fastlane otherwise
          # Keystore file '/home/runner/.gradle/daemon/7.3.3/debug.keystore' not found for signing config 'externalOverride'.
          KEY_PATH: ${{ github.workspace }}/android/app/debug.keystore
          KEY_STORE_PASSWORD: android
          KEY_ALIAS: androiddebugkey
          KEY_PASSWORD: android

  actionlint:
    name: Lint GitHub Actions workflows
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check workflow files
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
        shell: bash
